### ISSUE TITLE
mdr

### ISSUE THREAD

**Issue by GAGOU78** [r3ngan/Nighty-Selfbot-Premium-Free#1]
mdr tes malin toi c'est pas le nighty selfbot + c'est un skid du ghost selfbot

**Comment by Nshout** [comment]
c'est littéralement la source du ghost selfbot

**Comment by r3ngan** [comment]
cc cv, ghost selfbot = nighty selfbot bg

**Comment by GAGOU78** [comment]
mdr clairement pas

**Comment by r3ngan** [comment]
si, mon ami a le premium est c'est identique :)
